[project]
name = "keylogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "keyboard>=0.13.5",
    "psutil>=7.0.0",
    "pyinstaller>=6.13.0",
    "pywin32>=310",
    "requests>=2.32.3",
]
